data:
  raw_excel: "https://docs.google.com/spreadsheets/d/191QX-rsCOfm9dmlQb4UHMoVHwnEBm9tG/edit?usp=sharing&ouid=103873465285891206693&rtpof=true&sd=true"
  processed_base1: "data/processed/base1"
  processed_base2: "data/processed/base2"

windows:
  months_stage: 6   # janela p/ métricas de estágio

domains:
  ds_tran_map:
    PIX: "PIX"
    TED: "TED"
    BOLETO: "BOLETO"
    SISTEMICO: "OUTROS"
    default: "OUTROS"